export default [{
    id: 1,
    question: "What is the best movie of 2023 so far?",
    choices: [
      "The Fabelmans",
      "Elvis",
      "Top Gun: Maverick",
      "The Banshees of Inisherin",
    ],
    answer: 0,
  },
  {
    id: 2,
    question: "What is the highest-grossing movie of 2023?",
    choices: [
      "Avatar: The Way of Water",
      "Top Gun: Maverick",
      "Jurassic World Dominion",
      "The Batman",
    ],
    answer: 1,
  },
  {
    id: 3,
    question: "What is the most critically acclaimed movie of 2023?",
    choices: [
      "The Fabelmans",
      "Elvis",
      "Top Gun: Maverick",
      "The Banshees of Inisherin",
    ],
    answer: 3,
  },
  {
    id: 4,
    question: "What is the most anticipated movie of 2023?",
    choices: [
      "Spider-Man: Across the Spider-Verse",
      "The Flash",
      "Guardians of the Galaxy Vol. 3",
      "John Wick: Chapter 4",
    ],
    answer: 1,
  },
  {
    id: 5,
    question: "What is the best animated movie of 2023?",
    choices: [
      "Lightyear",
      "Turning Red",
      "The Bad Guys",
      "Marcel the Shell with Shoes On",
    ],
    answer: 2,
  },
  {
    id: 6,
    question: "What is the best superhero movie of 2023?",
    choices: [
      "The Flash",
      "Guardians of the Galaxy Vol. 3",
      "Black Panther: Wakanda Forever",
      "Ant-Man and the Wasp: Quantumania",
    ],
    answer: 1,
  },
  {
    id: 7,
    question: "What is the best horror movie of 2023?",
    choices: [
      "Nope",
      "The Black Phone",
      "Salem's Lot",
      "The Exorcist: The Beginning",
    ],
    answer: 3,
  },
  {
    id: 8,
    question: "What is the best comedy movie of 2023?",
    choices: [
      "Barbie",
      "Top Gun: Maverick",
      "The Adam Project",
      "Everything Everywhere All at Once",
    ],
    answer: 2,
  },
  {
    id: 9,
    question: "What is the best drama movie of 2023?",
    choices: ["Tár", "The Fabelmans", "Elvis", "The Banshees of Inisherin"],
    answer: 0,
  },
  {
    id: 10,
    question: "What is the best foreign language movie of 2023?",
    choices: ["Triangle of Sadness", "EO", "Close", "The Quiet Girl"],
    answer: 1,
  },
]  
